voiestad/f1-gjettespill-backend

src/main/java/no/vebb/f1/config/SQLiteConfig.java, src/main/java/no/vebb/f1/controller/AdminController.java, src/main/java/no/vebb/f1/controller/RankingController.java, src/main/java/no/vebb/f1/importing/Importer.java, src/main/resources/templates/addCompetitors.html
Sjåfører og konstruktører kan legges til før sesongstart i en gitt rekkefølge som tipperne får opp når de skal tippe rekkefølgen på mesterskapet før sesongen.
=> Register season competitors

src/main/java/no/vebb/f1/config/SQLiteConfig.java, src/main/java/no/vebb/f1/controller/AdminController.java, src/main/java/no/vebb/f1/controller/ScoreController.java, src/main/resources/templates/managePointsSystem.html
Laget side der admin kan endre poengsystemet for hver sesong
=> Manage points system

src/main/java/no/vebb/f1/controller/HomeController.java, src/main/resources/templates/public.html
Lagt til liste av årets deltakere på forsiden som vises frem til tippingene er offentlige
=> Display season guessers

src/main/java/no/vebb/f1/controller/AdminController.java, src/main/java/no/vebb/f1/controller/ScoreController.java, src/main/java/no/vebb/f1/importing/Importer.java, src/main/resources/templates/manageSeason.html, src/main/resources/templates/tables.html
Lagt til side for å se hvilken informasjon som ligger inne for et gitt løp og knapp for å laste inn informasjonen på nytt
=> Admin race info

src/main/java/no/vebb/f1/controller/RankingController.java, src/main/java/no/vebb/f1/controller/UsernameController.java
Fjernet logging av informasjon av hva som faktisk er tippet. Tidligere ble det logget hva som ble tippet av deltakerne på flagg og tipping av race
=> Logging fix

src/main/java/no/vebb/f1/controller/UserSettingsController.java, src/main/java/no/vebb/f1/controller/UsernameController.java, src/main/resources/templates/deleteAccount.html, src/main/resources/templates/header.html, src/main/resources/templates/registerUsername.html
Lagt til innstillinger hvor brukere kan endre brukernavn og slette brukeren sin
=> User settings

.gitignore, src/main/java/no/vebb/f1/database/DatabaseBackup.java
Tar backup av databasen ved oppstart, hvert døgn og avslåing
=> Backup av database

README.md, src/main/java/no/vebb/f1/components/BreadcrumbInterceptor.java, src/main/java/no/vebb/f1/components/NotificationMail.java, src/main/java/no/vebb/f1/config/SQLiteConfig.java, src/main/java/no/vebb/f1/controller/user/UserSettingsController.java, src/main/java/no/vebb/f1/database/Database.java, src/main/java/no/vebb/f1/user/UserMail.java, src/main/java/no/vebb/f1/user/UserMailService.java, src/main/java/no/vebb/f1/util/VerificationCodeGenerator.java, src/main/java/no/vebb/f1/util/exception/InvalidEmailException.java, src/main/resources/application.properties, src/main/resources/templates/mail.html, src/main/resources/templates/verificationCode.html
Lagt til valgfrie e-post påminnelser
=> Mailing List

src/main/java/no/vebb/f1/user/UserMail.java, src/main/resources/templates/mail.html, src/main/resources/templates/verificationCode.html
- Oppdatert regex til mail for å støtte eksempel+f1tipping@epost.no
- Validerer input på verifikasjonskode
=> Mail regex

src/main/resources/static/list.css, src/main/resources/templates/ranking.html
Forbedret brukergrensesnittet for å rangere sjåfører og konstruktører.
Gjort det mer robust ved å kun oppdatere rekkefølgen når man slipper.
Gjort det visuelt bedre ved å bruke animasjoner.
=> Ranking UI improvements

src/main/java/no/vebb/f1/components/VerificationCodeRemover.java, src/main/java/no/vebb/f1/database/Database.java
Fjerner utgåtte verifikasjonskoder
=> Remove old verification codes

src/main/java/no/vebb/f1/components/BreadcrumbInterceptor.java, src/main/java/no/vebb/f1/config/SecurityConfig.java, src/main/java/no/vebb/f1/controller/HomeController.java, src/main/java/no/vebb/f1/controller/user/UserSettingsController.java, src/main/java/no/vebb/f1/database/Database.java, src/main/java/no/vebb/f1/util/domainPrimitive/Category.java, src/main/resources/templates/about.html, src/main/resources/templates/contact.html, src/main/resources/templates/footer.html, src/main/resources/templates/privacy.html
=> Privacy declaration

src/main/java/no/vebb/f1/components/NotificationMail.java, src/main/java/no/vebb/f1/config/SQLiteConfig.java, src/main/java/no/vebb/f1/controller/user/UserSettingsController.java, src/main/java/no/vebb/f1/database/Database.java, src/main/java/no/vebb/f1/util/domainPrimitive/MailOption.java, src/main/java/no/vebb/f1/util/exception/InvalidMailOptionException.java, src/main/resources/static/loader.css, src/main/resources/static/tables.css, src/main/resources/templates/addSeason.html, src/main/resources/templates/mail.html, src/main/resources/templates/privacy.html
Brukerene styrer selv hvor mange påminnelser de vil få og når de ønsker å få de
=> Multiple reminders

src/main/java/no/vebb/f1/importing/Importer.java
Fiks for #28.
Flytter diskvalifiserte sjåfører bakerst.
=> Dsq race result fix

src/main/java/no/vebb/f1/components/HeaderInterceptor.java, src/main/resources/templates/header.html
Viser kun "Tipping" i headeren når det er noe å tippe på
=> Hide guessing from header

src/main/java/no/vebb/f1/components/BreadcrumbInterceptor.java, src/main/java/no/vebb/f1/controller/ProfileController.java, src/main/java/no/vebb/f1/database/Database.java, src/main/java/no/vebb/f1/scoring/UserScore.java, src/main/resources/templates/compare.html, src/main/resources/templates/header.html
Head-to-head sammenligning av brukere sine gjettinger.
=> Compare guesses

src/main/java/no/vebb/f1/F1Application.java, src/main/java/no/vebb/f1/controller/GuessController.java, src/main/java/no/vebb/f1/controller/admin/FlagController.java, src/main/java/no/vebb/f1/controller/admin/season/CutoffController.java, src/main/java/no/vebb/f1/controller/admin/season/ManagePointsSystemController.java, src/main/java/no/vebb/f1/controller/admin/season/ManageSeasonController.java, src/main/java/no/vebb/f1/controller/admin/season/SeasonCompetitorsController.java, src/main/java/no/vebb/f1/controller/admin/season/SeasonController.java, src/main/java/no/vebb/f1/controller/user/UserSettingsController.java, src/main/java/no/vebb/f1/controller/user/UsernameController.java, src/main/java/no/vebb/f1/importing/Importer.java
Lagt til transaksjoner på muterende handlinger til databasen
=> Transactions

src/main/java/no/vebb/f1/components/BreadcrumbInterceptor.java, src/main/java/no/vebb/f1/config/SecurityConfig.java, src/main/java/no/vebb/f1/controller/StatsController.java, src/main/java/no/vebb/f1/controller/admin/season/ManageSeasonController.java, src/main/java/no/vebb/f1/database/Database.java, src/main/java/no/vebb/f1/util/StatsUtil.java, src/main/java/no/vebb/f1/util/collection/RegisteredFlag.java, src/main/resources/templates/header.html
Gjort statistikk fra løpene tilgjengelig for alle
=> Public stats

src/main/java/no/vebb/f1/importing/Importer.java
Laster inn standings når løpet som lastes inn manuelt er det nyeste løpet
=> Manually reload standings

src/main/java/no/vebb/f1/components/SavedRequestFilter.java, src/main/java/no/vebb/f1/config/SecurityConfig.java, src/main/resources/static/style.css, src/main/resources/templates/footer.html, src/main/resources/templates/header.html
- Når man logger inn kommer man tilbake til samme siden man kom fra i stedet for /.
- Headeren er delt opp i undermenyer
=> Navigation improvements

src/main/resources/templates/header.html
Endret ikon til ikon som er synlig på mobil
=> Navigation icon fix

src/main/java/no/vebb/f1/controller/BingoController.java
Lagt til bindestrek i bingo alfabetet
=> Bingo hypen

src/main/java/no/vebb/f1/config/SQLiteConfig.java, src/main/java/no/vebb/f1/controller/admin/FlagController.java, src/main/java/no/vebb/f1/database/Database.java, src/main/java/no/vebb/f1/util/StatsUtil.java, src/main/java/no/vebb/f1/util/collection/RegisteredFlag.java, src/main/java/no/vebb/f1/util/domainPrimitive/SessionType.java, src/main/java/no/vebb/f1/util/exception/InvalidSessionTypeException.java, src/main/resources/templates/noteFlags.html
Lagt til hvilken type økt et flagg ble registrert i for å skille mellom flagg i løp og sprint
=> Flag register session

src/main/java/no/vebb/f1/config/SQLiteConfig.java, src/main/java/no/vebb/f1/controller/admin/season/SeasonCompetitorsController.java, src/main/java/no/vebb/f1/database/Database.java, src/main/java/no/vebb/f1/importing/Importer.java, src/main/resources/templates/addCompetitors.html
Lagt til muligheten for å legge til alternative navn på sjåfører.
Fikser #47
=> Alternative driver names

.gitignore, src/main/resources/logback-spring.xml
Logger til filer. En fil for INFO og en for ERROR og WARN. Ny fil for hver dag.
=> File logging

src/main/java/no/vebb/f1/components/BreadcrumbInterceptor.java, src/main/java/no/vebb/f1/controller/admin/AdminController.java, src/main/java/no/vebb/f1/controller/admin/LogController.java, src/main/resources/templates/text.html
Logger tilgjenglig fra admin portal
=> Log in admin portal

src/main/java/no/vebb/f1/controller/admin/LogController.java, src/main/resources/logback-spring.xml
Bytter fil som logges til for hver dag
=> Log rolling policy

src/main/java/no/vebb/f1/controller/admin/FlagController.java, src/main/resources/static/style.css, src/main/resources/templates/noteFlags.html
Forbedret brukergrensesnittet for å notere flagg.
- Drop down meny byttet ut med radio knapper for flaggtypen.
- Tall input byttet ut med slider.
- Type økt, flagg og runde blir husket fra forrige notering.
=> Note flags UI

src/main/java/no/vebb/f1/controller/HomeController.java
Hvis to personer har like mange poeng får de samme plassering på ledertavlen
=> Leaderboard equal on points

src/main/resources/templates/header.html
Update url for page with previous results
=> Update url for f1-old

src/main/java/no/vebb/f1/controller/admin/LogController.java
Sort logs by date and print logs in reverse
=> Sorted logs

src/main/java/no/vebb/f1/database/Database.java, src/main/java/no/vebb/f1/importing/Importer.java, src/main/java/no/vebb/f1/user/UserMailService.java
Add ResultChangeStatus and message admins when OUTSIDE_POINTS_CHANGE happens without change in standings.
Change in points still require change in standings to import.
=> Import change outside points

src/main/java/no/vebb/f1/components/BreadcrumbInterceptor.java, src/main/java/no/vebb/f1/controller/admin/AdminApiController.java, src/main/java/no/vebb/f1/controller/admin/AdminController.java, src/main/resources/static/style.css, src/main/resources/templates/backup.html
Add download backup for admin so that admin can create external backups
=> External backup

src/main/java/no/vebb/f1/components/HeaderInterceptor.java, src/main/java/no/vebb/f1/controller/user/UsernameController.java, src/main/resources/templates/deleteAccount.html, src/main/resources/templates/registerUsername.html
Add logout button for new users registering
=> Logout as new user

src/main/java/no/vebb/f1/components/NotificationMail.java, src/main/java/no/vebb/f1/components/VerificationCodeRemover.java, src/main/java/no/vebb/f1/controller/HomeController.java, src/main/java/no/vebb/f1/controller/admin/season/CutoffController.java, src/main/java/no/vebb/f1/database/DatabaseBackup.java, src/main/java/no/vebb/f1/graph/Graph.java, src/main/java/no/vebb/f1/graph/GraphCache.java, src/main/java/no/vebb/f1/importing/Importer.java, src/main/java/no/vebb/f1/util/TimeUtil.java, src/main/resources/templates/public/index.html
Decreases loading times for home page
=> Cache graph and leaderboard

src/main/resources/application.properties
Add caching of static resources with automatic versioning
=> Cache static resources

src/main/resources/templates/header.html
Const variable in header renamed from button to themeButton to avoid naming collision in backup
=> Backup button fix

src/main/resources/templates/guess/chooseDriver.html
Moved h2 element inside main element in chooseDriver.html. The styling was not applied correctly when it was outside
=> Element outside main html fix

src/main/java/no/vebb/f1/importing/Importer.java
Validate that change in points is correct when importing standings. This is to assure that change in points isn't caused by a sprint
=> Point change import

src/main/java/no/vebb/f1/components/CodeRemover.java, src/main/java/no/vebb/f1/components/NotificationMail.java, src/main/java/no/vebb/f1/database/Database.java, src/main/java/no/vebb/f1/database/DatabaseBackup.java, src/main/java/no/vebb/f1/graph/GraphCache.java, src/main/java/no/vebb/f1/importing/ImportSchedulingConfig.java, src/main/java/no/vebb/f1/importing/Importer.java
Added variable import delays for importing data.
Imports more often when it's race weekend and less when outside of race weekend.
=> Variable import delay

src/main/java/no/vebb/f1/controller/admin/LogController.java, src/main/java/no/vebb/f1/filters/GenericFilter.java, src/main/java/no/vebb/f1/filters/GraphCacheFilter.java, src/main/java/no/vebb/f1/filters/ImporterFilter.java, src/main/resources/logback-spring.xml
Add filters to extract importing and caching into separate logs
=> Filter logging

src/main/java/no/vebb/f1/importing/Importer.java
Instead of letting transactions automatically roll back in Importer, all exceptions are manually caught and transactions manually rolled back. This is to log the exception to the import-logger instead of the main loggers.
Exceptions for parsing are also caught to be thrown again with more verbose error messages.
=> Import exception handling

src/main/java/no/vebb/f1/database/Database.java
Fix infinite recursion in getTimeLeftToGuessRaceHours
=> Fix infinite recursion

pom.xml
Add finalName to build in pom.xml to have a static name
=> Final name pom

src/main/java/no/vebb/f1/database/Database.java, src/main/java/no/vebb/f1/graph/GuesserPointsSeason.java, src/main/java/no/vebb/f1/scoring/ScoreCalculator.java, src/main/java/no/vebb/f1/util/collection/RankedGuesser.java
Calculate score for all users and filter out users with no score from leaderboard and graph
=> Join mid season
